service: authorization-service

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  basicAuthorizer:
    handler: basicAuthorizer/handler.basicAuthorizer
    events:
      - httpApi:
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors: true
