service: import-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

  environment:
    SQS_URL:
      Fn::ImportValue: product-service-dev-catalogItemsQueueUrl
    SQS_ARN:
      Fn::ImportValue: product-service-dev-catalogItemsQueueArn

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - arn:aws:s3:::import-service-labetik-s3
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - arn:aws:s3:::import-service-labetik-s3/*
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource:
        - Fn::ImportValue: product-service-dev-catalogItemsQueueArn

functions:
  importProductsFile:
    handler: importProductsFile/handler.importProductsFile
    events:
      - http:
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors: true
          authorizer:
            name: basicAuthorizer
            arn:
              Fn::ImportValue: authorization-service-dev-basicAuthorizerArn
            type: token
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  importFileParser:
    handler: importFileParser/handler.importFileParser
    events:
      - s3:
          bucket: import-service-labetik-s3
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
